CREATE TABLE IF NOT EXISTS Login
(
  Username VARCHAR,
  Pwd VARCHAR NOT NULL,
  IP VARCHAR NOT NULL,
  Auth_key NUMERIC,
  PORT NUMERIC
  PRIMARY KEY (Username),
  UNIQUE (IP),
  UNIQUE (PORT),
  UNIQUE (Auth_key),
  CHECK (PORT >= 10200 AND PORT <= 10400)
);